services:
  postgres:
    container_name: r_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: class
      POSTGRES_PASSWORD: class123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: r_mail_dev
    image: maildev/maildev
    ports:
     - 1080:1080
     - 1025:1025
    networks:
      - microservices-net
  keycloak:
    container_name: keycloak-res
    image: quay.io/keycloak/keycloak:26.2.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    command:
      - "start-dev"

  restaurant-api:
    container_name: restaurant-api
    image: restaurant/restaurant:1.0.0
    ports:
      - 8088:8088
    networks:
      - microservices-net
    depends_on:
      - postgres
  restaurant-ui:
    container_name: restaurant-ui
    image: restaurant/restaurant-client-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - microservices-net
    depends_on:
      - restaurant-api

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:

