name: RES Backend API Pipeline

on:
  push:
    paths:
      - backend/restaurant-backend/**
      - frontend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    environment: dev
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Debug structure
        run: |
          pwd
          ls -R | head -50
          pwd

      - name: Compile project
        run: |
          cd backend/restaurant-backend
          chmod +x mvnw
          ./mvnw clean compile

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
         java-version: 21
         distribution: 'corretto'
      - name: Running Unit Tests
        run: |
         cd backend/restaurant-backend
         ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build Backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Build project
        run: |
          cd backend/restaurant-backend
          ./mvnw clean package

  build-image:
    name: Build & Push Docker to ECR
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Extract project version
        id: extract_version
        run: |
          cd backend/restaurant-backend
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      - name: Debug AWS secrets
        run: |
         echo "AWS key length: ${#AWS_ACCESS_KEY_ID}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

      # ðŸ” Login AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # ðŸ” Login ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # ðŸ³ Build + Push image
      - name: Build & Push Docker image to ECR
        run: |
          IMAGE_URI=701970276292.dkr.ecr.eu-north-1.amazonaws.com/restaurant-api
          VERSION=${{ steps.extract_version.outputs.VERSION }}

          docker build \
            --build-arg PROFILE=dev \
            --build-arg APP_VERSION=$VERSION \
            -t $IMAGE_URI:$VERSION \
            -t $IMAGE_URI:latest \
            -f docker/backend/Dockerfile \
            backend/restaurant-backend

          docker push $IMAGE_URI:$VERSION
          docker push $IMAGE_URI:latest

  deploy:
    name: Deploy Backend API on ECS
    runs-on: ubuntu-latest
    needs: [ build-image ]
    environment: dev
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition restaurant-api-task-dev \
            --query taskDefinition > task-definition.json

      - name: Update image in task definition
        run: |
          VERSION=$(jq -r '.containerDefinitions[0].image' task-definition.json | cut -d':' -f2)
          NEW_IMAGE="701970276292.dkr.ecr.eu-north-1.amazonaws.com/restaurant-api:${{ needs.build-image.outputs.VERSION }}"

          jq --arg IMAGE "$NEW_IMAGE" \
            '.containerDefinitions[0].image = $IMAGE |
             del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)' \
             task-definition.json > new-task-definition.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json

      - name: Deploy new revision
        run: |
          aws ecs update-service \
            --cluster restaurant-cluster-dev \
            --service restaurant-api-dev \
            --force-new-deployment
## 701970276292.dkr.ecr.eu-north-1.amazonaws.com/restaurant-api
