name: RES Backend API Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - backend/restaurant-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Compile project
        run: |
          cd backend/restaurant-backend
          ./mvnw clean compile


  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java
        with:
         java-version: 21
         distribution: 'corretto'
      - name: Running Unit Tests
        run: |
         cd backend/restaurant-backend
         ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build Backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Build project
        run: |
          cd backend/restaurant-backend
          ./mvnw clean package

  build-image:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Extract project version
        id: extract_version
        run: |
          cd  backend/restaurant-backend
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: restaurant-backend
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/bsn-api:${{steps.extract_version.outputs.VERSION}},${{secrets.DOCKERHUB_USERNAME}}/bsn-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{steps.extract_version.outputs.VERSION}}

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Create deployment folder
        run: ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPN_IP}} "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: scp docker-compose.yml ${{secrets.VPS_USERNAME}}@${{secrets.VPN_IP}}:ci-cd/docker-compose.yml

      - name: set ENV variable and deploy
        run: |
          ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPN_IP}} <<EOF
          export EMAIL_HOSTNAME=${{secrets.EMAIL_HOSTNAME}}
          export EMAIL_USER_NAME=${{secrets.EMAIL_USER_NAME}}
          export EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF


